version = 1

test_patterns = ["tests/*/test_*.py", "tests/test_*.py", "tests/conftest.py"]

exclude_patterns = ["docs/*.py"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements_dev.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true
