# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  apt_packages:
    - openslide-tools
    - libopenjp2-7-dev
    - libopenjp2-tools

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
      - requirements: requirements/requirements.txt
      - requirements: docs/requirements.txt
