[package]
name = "tiatoolbox"
version = "0.1.0"
edition = "2024"
autolib = false

[lib]
path = "tiatoolbox/rust-library/lib.rs"
name = "rust_misc"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.17.2"
numpy = "0.29.0"
ordered-float = "5.3.0"
pyo3 = "0.29.2"
pythonize = "0.29.0"
serde_json = "1.0.151"
