openapi: 3.0.0
info:
  title: tiatoolbox tileserver API
  version: 1.0.0
  description: A simple API to get tiles from a WSI, together with rendered
    annotations. Provides endpoints to get tiles from different layers,
    specify the path to the resource to be displayed, and control aspects of the
    AnnotationRenderer used to render the annotations.

paths:
  /tileserver/layer/{layer}/{user}/zoomify/TileGroup{tile_group}/{z}-{x}-{y}@{res}x.jpg:
    get:
      summary: Get zoomify tiles for a layer
      parameters:
        - in: path
          name: layer
          description: Name of the layer
          required: true
          schema:
            type: string
        - in: path
          name: user
          description: Name of the user
          required: true
          schema:
            type: string
        - in: path
          name: tile_group
          description: Number of the TileGroup
          required: true
          schema:
            type: integer
        - in: path
          name: z
          description: Zoom level
          required: true
          schema:
            type: integer
        - in: path
          name: x
          description: X coordinate of the tile
          required: true
          schema:
            type: integer
        - in: path
          name: y
          description: Y coordinate of the tile
          required: true
          schema:
            type: integer
        - in: path
          name: res
          description: Resolution of the tile (1 or 2x)
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Image returned successfully
          content:
            image/webp:
              schema:
                type: image/webp

  /:
    get:
      summary: Get index page
      responses:
        '200':
          description: Successful response

  /tileserver/get_user:
    get:
      summary: Get user information
      responses:
        '200':
          description: Successful response

  /tileserver/change_color_prop/{prop}:
    put:
      summary: Update property to color annotations by
      parameters:
        - in: path
          name: prop
          description: Name of the property
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response

  /tileserver/change_slide/{slide_path}:
    put:
      summary: change the base slide. All overlays will be removed.
      parameters:
        - in: path
          name: slide_path
          description: Path to the slide in url safe form
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response

  /tileserver/change_cmap/{cmap}:
    put:
      summary: Change colormap for a layer
      parameters:
        - in: path
          name: cmap
          description: Name of the colormap, should be a matplotlib colormap
            or a dict string
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response

  /tileserver/load_annotations/{file_path}/{model_mpp}:
    put:
      summary: Load annotations for a slide
      parameters:
        - in: path
          name: file_path
          description: Path to the annotation file in url safe form
            can be a .db, .dat or .geojson file
          required: true
          schema:
            type: string
        - in: path
          name: model_mpp
          description: Model microns per pixel, used if annotations are output
            of a model not at baseline
          required: true
          schema:
            type: number
            format: float
      responses:
        '200':
          description: Successful response

  /tileserver/change_overlay/{overlay_path}:
    put:
      summary: Change overlay image for a slide
      parameters:
        - in: path
          name: overlay_path
          description: Path to the new overlay image file
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response

  /tileserver/commit/{save_path}:
    get:
      summary: Commit database changes
      parameters:
        - in: path
          name: save_path
          description: Url safe path to save the database changes
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response

  /tileserver/update_renderer/{prop}/{val}:
    put:
      summary: Update annotation renderer properties
      parameters:
        - in: path
          name: prop
          description: Property to update
          required: true
          schema:
            type: string
        - in: path
          name: val
          description: New value for the property
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response

  /tileserver/change_secondary_cmap/{type_id}/{prop}/{cmap}:
    put:
      summary: Change secondary color map for a property type
      parameters:
        - in: path
          name: type_id
          description: The type for which you want to override the primary
            color map
          required: true
          schema:
            type: string
        - in: path
          name: prop
          description: Property to use to color annotations of the chose type
          required: true
          schema:
            type: string
        - in: path
          name: cmap
          description: Color map to use for the property
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response

  /tileserver/get_prop_names:
    get:
      summary: Get a list of available property names
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  properties:
                    type: array
                    items:
                      type: string

  /tileserver/get_prop_values/{prop}/{ann_type}:
    get:
      summary: Get a list of available values for a property
      parameters:
        - in: path
          name: prop
          description: Name of the property to retrieve values for
          required: true
          schema:
            type: string
        - in: path
          name: type
          description: Name of a type to retrieve property values for.
            if all, prop values over all annotations will be returned
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  values:
                    type: array
                    items:
                      type: string

  /tileserver/reset:
    get:
      summary: Remove no longer needed objects if user closed the browser
      responses:
        '200':
          description: Successful response
