"""Reader for fsspec zarr JSON generated files."""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

import fsspec
import numpy as np
import zarr
from fsspec.implementations.reference import ReferenceFileSystem
from imagecodecs.numcodecs import Delta, Jpeg, Jpeg2k, Lzw
from numcodecs import register_codec
from zarr.experimental.cache_store import CacheStore
from zarr.storage import FsspecStore, MemoryStore

from tiatoolbox import logger
from tiatoolbox.wsicore.wsimeta import WSIMeta

from .base import ArrayView, WSIReader
from .tiff import TIFFWSIReaderDelegate

if TYPE_CHECKING:  # pragma: no cover
    from numbers import Number

    from tiatoolbox.type_hints import IntBounds, IntPair, Resolution, Units


class FsspecJsonWSIReader(WSIReader):
    """Reader for fsspec zarr JSON generated by: tiatoolbox/utils/tiff_to_fsspec.py.

    The fsspec zarr JSON file represents a SVS or TIFF file
    that be accessed using byte range HTTP API.

    All the information on the chunk locations in the SVS or TIFF file
    is outlined as byte-ranges in the JSON,
    so the reader requests only chunks that are needed to display requested tiles,
    rather than the entire SVS or TIFF file.

    """

    def __init__(
        self: FsspecJsonWSIReader,
        input_img: str | Path | np.ndarray,
        mpp: tuple[Number, Number] | None = None,
        power: Number | None = None,
        cache_size: int = 2**28,
    ) -> None:
        """Initialize :class:`FsspecJsonWSIReader`."""
        super().__init__(input_img=input_img, mpp=mpp, power=power)

        # ------- Register codecs --------
        register_codec(Jpeg(), "imagecodecs_jpeg")
        register_codec(Jpeg2k(), "imagecodecs_jpeg2k")
        register_codec(Lzw(), "imagecodecs_lzw")
        register_codec(Delta(), "imagecodecs_delta")

        # Create an async ReferenceFileSystem directly to avoid the
        # asynchronous mismatch when zarr v3 calls FsspecStore.from_mapper()
        # (see https://github.com/zarr-developers/zarr-python/issues/3323).
        # Passing remote_options={"asynchronous": True} ensures that any
        # remote filesystem (e.g. HTTPFileSystem) is also created as async,
        # satisfying the invariant checked inside ReferenceFileSystem.__init__.
        ref_fs = ReferenceFileSystem(
            fo=str(input_img),
            target_protocol="file",
            remote_options={"asynchronous": True},
            asynchronous=True,
        )
        self._zarr_store = FsspecStore(fs=ref_fs, read_only=True, path="/")

        self._zarr_array = zarr.open(self._zarr_store, mode="r")

        self.__set_axes()

        cache_backend = MemoryStore()
        self._zarr_cache = CacheStore(
            store=self._zarr_store, cache_store=cache_backend, max_size=cache_size
        )
        self._zarr_group = zarr.open(self._zarr_cache)
        if isinstance(self._zarr_group, zarr.Group):  # pragma: no cover
            self.level_arrays = {
                int(key): ArrayView(array, axes=self._axes)
                for key, array in self._zarr_group.members()
            }
        else:  # pragma: no cover
            self.level_arrays = {0: ArrayView(self._zarr_group, axes=self._axes)}
        # ensure level arrays are sorted by descending area
        self.level_arrays = dict(
            sorted(
                self.level_arrays.items(),
                key=lambda x: (
                    -np.prod(
                        TIFFWSIReaderDelegate.canonical_shape(
                            self._axes, x[1].array.shape[:2]
                        )
                    )
                ),
            )
        )
        self.tiff_reader_delegate = TIFFWSIReaderDelegate(self, self.level_arrays)

    def __set_axes(self) -> None:  # pragma: no cover
        """Loads axes from the JSON file.

        In case zarr array has a group 0 at root,
        loads axes from the layer 0.

        In case the zarr array doesn't have a group 0 at
        root, loads axes from attrs at root.

        """
        if isinstance(self._zarr_array, zarr.Group):
            if "0" in self._zarr_array:
                zattrs = self._zarr_array["0"].attrs
                if "_ARRAY_DIMENSIONS" in zattrs:
                    self._axes = "".join(
                        zattrs["_ARRAY_DIMENSIONS"]
                    )  # Concatenate dimensions
                else:
                    msg = "'_ARRAY_DIMENSIONS' does not exist in the group '0'."
                    raise ValueError(msg)
            else:
                msg = "The group '0' does not exist in the zarr_array."
                raise ValueError(msg)
        else:
            zattrs_path = self._zarr_array.attrs
            if "_ARRAY_DIMENSIONS" in zattrs_path:
                self._axes = "".join(
                    zattrs_path["_ARRAY_DIMENSIONS"]
                )  # Concatenate dimensions
            else:
                msg = "'_ARRAY_DIMENSIONS' does not exist in the root .zattrs."
                raise ValueError(msg)

    @staticmethod
    def is_valid_zarr_fsspec(file_path: str) -> bool:
        """Check if the input path is a valid Zarr fsspec JSON file.

        Checks if the file_path is a valid Zarr fsspec JSON file generated by:
        tiatoolbox/utils/tiff_to_fsspec.py

        Args:
            file_path: str Path to the file to check.

        Returns:
            bool: True if the file is a valid Zarr fsspec JSON file
        """
        path = Path(file_path)

        if path.suffix.lower() != ".json":
            return False

        try:
            with fsspec.open(file_path, "r") as file:
                data = json.load(file)

            # Basic validation for fsspec Zarr JSON structure
            if ".zattrs" not in data:
                logger.error("Field .zattrs missing in '%s'.", file_path)
                return False

            return True  # noqa: TRY300

        except json.JSONDecodeError as e:
            logger.error("Invalid JSON file: %s", e)
            return False
        except (OSError, ValueError) as e:
            logger.error("An error occurred: %s", e)
            return False

    def _info(self: FsspecJsonWSIReader) -> WSIMeta:
        """TIFF metadata constructor.

        Returns:
            WSIMeta:
                Containing metadata.

        """
        level_count = len(self.level_arrays)
        level_dimensions = [
            np.array(
                TIFFWSIReaderDelegate.canonical_shape(self._axes, p.array.shape)[:2][
                    ::-1
                ]
            )
            for p in self.level_arrays.values()
        ]
        slide_dimensions = level_dimensions[0]
        level_downsamples = [(level_dimensions[0] / x)[0] for x in level_dimensions]

        zarr_attrs = self._zarr_array.attrs

        filetype_params = {}
        # Check for "multiscales" and extract metadata
        if "multiscales" in zarr_attrs:  # pragma: no cover
            multiscales = zarr_attrs[
                "multiscales"
            ]  # List of multiscale metadata entries
            for entry in multiscales:
                filetype_params = entry.get("metadata", {})

        # Fallback to calculating objective power & mpp
        objective_power, mpp = self._estimate_mpp_objective_power(
            objective_power=filetype_params["objective_power"],
            mpp=filetype_params["mpp"],
        )
        filetype_params["mpp"] = mpp
        filetype_params["objective_power"] = objective_power

        return WSIMeta(
            file_path=self.input_path,
            slide_dimensions=slide_dimensions,
            axes=self._axes,
            level_count=level_count,
            level_dimensions=level_dimensions,
            level_downsamples=level_downsamples,
            **filetype_params,
        )

    def read_rect(
        self: FsspecJsonWSIReader,
        location: IntPair,
        size: IntPair,
        resolution: Resolution = 0,
        units: Units = "level",
        interpolation: str = "optimise",
        pad_mode: str = "constant",
        pad_constant_values: int | IntPair = 0,
        coord_space: str = "baseline",
        **kwargs: dict,
    ) -> np.ndarray:
        """See TIFFWSIReaderDelegate.read_rect docs for details."""
        return self.tiff_reader_delegate.read_rect(
            location,
            size,
            resolution,
            units,
            interpolation,
            pad_mode,
            pad_constant_values,
            coord_space,
            **kwargs,
        )

    def read_bounds(
        self: FsspecJsonWSIReader,
        bounds: IntBounds,
        resolution: Resolution = 0,
        units: Units = "level",
        interpolation: str = "optimise",
        pad_mode: str = "constant",
        pad_constant_values: int | IntPair = 0,
        coord_space: str = "baseline",
        **kwargs: dict,
    ) -> np.ndarray:
        """See TIFFWSIReaderDelegate.read_bounds docs for details."""
        return self.tiff_reader_delegate.read_bounds(
            bounds,
            resolution,
            units,
            interpolation,
            pad_mode,
            pad_constant_values,
            coord_space,
            **kwargs,
        )
