"""Define GrandQC Tissue Detection Model architecture."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover
    from collections.abc import Mapping

import cv2
import numpy as np
import torch

from tiatoolbox.models.architecture.unetplusplus import UNetPlusPlusModel
from tiatoolbox.models.models_abc import ModelABC


class GrandQCModel(ModelABC):
    """GrandQC Tissue Detection Model [1].

    Example:
        >>> from tiatoolbox.models.engine.semantic_segmentor import SemanticSegmentor
        >>> semantic_segmentor = SemanticSegmentor(
        ...     model="grandqc_tissue_detection_mpp10",
        ... )
        >>> results = semantic_segmentor.run(
        ...     ["/example_wsi.svs"],
        ...     masks=None,
        ...     auto_get_mask=False,
        ...     patch_mode=False,
        ...     save_dir=Path("/tissue_mask/"),
        ...     output_type="annotationstore",
        ... )

    References:
        [1] Weng Z. et al. "GrandQC: a comprehensive solution to quality control problem
        in digital pathology".
        Nature Communications 2024

    """

    def __init__(
        self: GrandQCModel, num_input_channels: int, num_output_channels: int
    ) -> None:
        """Initialize TissueDetectionModel."""
        super().__init__()
        self.num_input_channels = num_input_channels
        self.num_output_channels = num_output_channels
        self._postproc = self.postproc
        self._preproc = self.preproc
        self.tissue_detection_model = UNetPlusPlusModel(
            classes=self.num_output_channels,
        )

    @staticmethod
    def preproc(image: np.ndarray) -> np.ndarray:
        """Apply JPEG compression and ImageNet normalization to the input image.

        Args:
            image (np.ndarray):
                Input image as a NumPy array (H, W, C) in uint8 format.

        Returns:
            np.ndarray:
                The preprocessed image.

        """
        encode_param = [int(cv2.IMWRITE_JPEG_QUALITY), 80]
        _, compressed_image = cv2.imencode(".jpg", image, encode_param)
        compressed_image = np.array(cv2.imdecode(compressed_image, 1))

        mean = np.array([0.485, 0.456, 0.406])
        std = np.array([0.229, 0.224, 0.225])
        return (compressed_image / 255.0 - mean) / std

    @staticmethod
    def postproc(image: np.ndarray) -> np.ndarray:
        """Define post-processing for this model.

        This simply applies argmin to obtain tissue class.
        (Tissue = 0, Background = 1)

        Args:
            image (np.ndarray):
                Input probability map as a NumPy array (H, W, C).

        Returns:
            np.ndarray:
                Tissue mask

        """
        return image.argmin(axis=-1)

    def forward(
        self: GrandQCModel,
        imgs: torch.Tensor,
        *args: tuple[Any, ...],  # skipcq: PYL-W0613  # noqa: ARG002
        **kwargs: dict,  # skipcq: PYL-W0613  # noqa: ARG002
    ) -> torch.Tensor:
        """Forward function for model."""
        return self.tissue_detection_model(imgs)

    @staticmethod
    def infer_batch(
        model: torch.nn.Module,
        batch_data: torch.Tensor,
        *,
        device: str,
    ) -> np.ndarray:
        """Run inference on an input batch.

        This contains logic for forward operation as well as i/o

        Args:
            model (nn.Module):
                PyTorch defined model.
            batch_data (:class:`torch.Tensor`):
                A batch of data generated by
                `torch.utils.data.DataLoader`.
            device (str):
                Transfers model to the specified device. Default is "cpu".

        Returns:
            np.ndarray:
                The inference results as a numpy array.

        """
        model.eval()

        imgs = batch_data
        imgs = imgs.to(device).type(torch.float32)
        imgs = imgs.permute(0, 3, 1, 2)  # to NCHW

        with torch.inference_mode():
            logits = model(imgs)
            probs = torch.nn.functional.softmax(logits, 1)
            probs = probs.permute(0, 2, 3, 1)  # to NHWC

        return probs.cpu().numpy()

    def load_state_dict(
        self: GrandQCModel,
        state_dict: Mapping[str, Any],
        **kwargs: bool,
    ) -> torch.nn.modules.module._IncompatibleKeys:
        """Load state dict for the GrandQCModel."""
        return self.tissue_detection_model.load_state_dict(state_dict, **kwargs)
