"""Define GrandQC Tissue Detection Model architecture."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Mapping

import cv2
import numpy as np
import segmentation_models_pytorch as smp
import torch

from tiatoolbox.models.models_abc import ModelABC


class TissueDetectionModel(ModelABC):
    """GrandQC Tissue Detection Model."""

    def __init__(self: TissueDetectionModel) -> None:
        """Initialize TissueDetectionModel."""
        super().__init__()
        self._postproc = self.postproc
        self._preproc = self.preproc
        self.tissue_detection_model = smp.UnetPlusPlus(
            encoder_name="timm-efficientnet-b0",
            encoder_weights=None,
            classes=2,
            activation=None,
        )

    @staticmethod
    def preproc(image: np.ndarray) -> np.ndarray:
        """Apply jpg compression then ImageNet normalise."""
        encode_param = [int(cv2.IMWRITE_JPEG_QUALITY), 80]
        _, compressed_image = cv2.imencode(".jpg", image, encode_param)
        compressed_image = np.array(cv2.imdecode(compressed_image, 1))

        mean = np.array([0.485, 0.456, 0.406])
        std = np.array([0.229, 0.224, 0.225])
        return (compressed_image / 255.0 - mean) / std

    @staticmethod
    def postproc(image: np.ndarray) -> np.ndarray:
        """Define post-processing of this class of model.

        This simply applies argmin along last axis of the input.

        """
        return image.argmin(axis=-1)

    def forward(
        self: TissueDetectionModel,
        imgs: torch.Tensor,
        *args: tuple[Any, ...],  # skipcq: PYL-W0613  # noqa: ARG002
        **kwargs: dict,  # skipcq: PYL-W0613  # noqa: ARG002
    ) -> torch.Tensor:
        """Forward function for model."""
        return self.tissue_detection_model(imgs)

    @staticmethod
    def infer_batch(
        model: torch.nn.Module,
        batch_data: torch.Tensor,
        *,
        device: str,
    ) -> np.ndarray:
        """Run inference on an input batch.

        This contains logic for forward operation as well as i/o

        Args:
            model (nn.Module):
                PyTorch defined model.
            batch_data (:class:`torch.Tensor`):
                A batch of data generated by
                `torch.utils.data.DataLoader`.
            device (str):
                Transfers model to the specified device. Default is "cpu".

        Args:
            model (nn.Module):
                PyTorch defined model.
            batch_data (:class:`torch.Tensor`):
                A batch of data generated by
                `torch.utils.data.DataLoader`.
            device (str):
                Transfers model to the specified device. Default is "cpu".

        Returns:
            np.ndarray:
                The inference results as a numpy array.

        """
        model.eval()

        ####
        imgs = batch_data

        imgs = imgs.to(device).type(torch.float32)
        imgs = imgs.permute(0, 3, 1, 2)  # to NCHW

        with torch.inference_mode():
            logits = model(imgs)
            probs = torch.nn.functional.softmax(logits, 1)
            probs = probs.permute(0, 2, 3, 1)  # to NHWC

        return probs.cpu().numpy()

    def load_state_dict(
        self: TissueDetectionModel,
        state_dict: Mapping[str, Any],
        **kwargs: bool,
    ) -> torch.nn.modules.module._IncompatibleKeys:
        """Load state dict for the TissueDetectionModel."""
        return self.tissue_detection_model.load_state_dict(state_dict, **kwargs)
