"""Define SAM architecture."""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
import torch
from segment_anything import SamAutomaticMaskGenerator, SamPredictor, sam_model_registry

from tiatoolbox.models.models_abc import ModelABC

if TYPE_CHECKING:  # pragma: no cover
    from tiatoolbox.type_hints import IntBounds, IntPair


class SAM(ModelABC):
    """Segment Anything Model (SAM) Architecture.

    Meta AI's zero-shot segmentation model.
    SAM is used for interactive general-purpose segmentation.

    Currently supports SAM, which requires a checkpoint and model type.

    SAM accepts an RGB image patch along with a list of point and bounding
    box coordinates as prompts.

    Args:
        model_type (str):
            Model type.
            Currently supported: vit_b, vit_l, vit_h.
        checkpoint_path (str):
            Path to the model checkpoint.
        device (str):
            Device to run inference on.

    Examples:
        >>> # instantiate SAM with checkpoint path and model type
        >>> sam = SAM(
        ...     model_type="vit_b",
        ...     checkpoint_path="path/to/sam_checkpoint.pth"
        ... )
    """

    def __init__(
        self: SAM,
        model_type: str = "vit_b",
        checkpoint_path: str | None = None,
        *,
        device: str = "cpu",
    ) -> None:
        """Initialize :class:`SAM`."""
        super().__init__()
        self.net_name = "SAM"
        self.device = device

        self.model = sam_model_registry[model_type](checkpoint=checkpoint_path).to(
            device
        )
        self.predictor = SamPredictor(self.model)
        self.generator = SamAutomaticMaskGenerator(self.model)

    def forward(
        self: SAM,
        imgs: list,
        point_coords: np.array | None = None,
        box_coords: np.array | None = None,
    ) -> np.ndarray:
        """Torch method. Defines forward pass on each image in the batch.

        Note: This architecture only uses a single layer, so only one forward pass
        is needed.

        Args:
            imgs (list):
                List of images to process, of the shape NHWC.
            point_coords (list):
                List of point coordinates for each image.
            box_coords (list):
                Bounding box coordinates for each image.

        Returns:
            list:
                List of masks and scores for each image.

        """
        batch_masks, batch_scores = [], []

        for i, image in enumerate(imgs):
            self._encode_image(image)

            # assume that prompts will be provided for all images in a batch
            points = point_coords[i] if point_coords is not None else None
            box = box_coords[i] if box_coords is not None else None

            if points is not None or box is not None:
                point_labels = np.ones(points.shape[0]) if points is not None else None
                masks, scores, _ = self.predictor.predict(
                    point_coords=points,
                    point_labels=point_labels,
                    box=box,
                    multimask_output=False,
                )
            else:
                # Use SAM's automatic mask generator
                masks = self.generator.generate(image)
                scores = np.array([mask["predicted_iou"] for mask in masks])
                masks = np.array(
                    [mask["segmentation"] for mask in masks], dtype=np.uint8
                )

            sorted_ind = np.argsort(scores)[::-1]
            sorted_masks = np.array(masks[sorted_ind], dtype=np.uint8)
            sorted_scores = np.around(scores[sorted_ind], 2)
            batch_masks.append(sorted_masks)
            batch_scores.append(sorted_scores)

        return batch_masks, batch_scores

    @staticmethod
    def infer_batch(
        model: torch.nn.Module,
        batch_data: list,
        point_coords: list[list[IntPair]] | None = None,
        box_coords: list[IntBounds] | None = None,
        *,
        device: str = "cpu",
    ) -> np.ndarray:
        """Run inference on an input batch.

        Contains logic for forward operation as well as I/O aggregation.
        SAM accepts a list of points and a single bounding box per image.

        Args:
            model (nn.Module):
                PyTorch defined model.
            batch_data (list):
                A batch of data generated by
                `torch.utils.data.DataLoader`.
            point_coords (list):
                Point coordinates for each image in the batch.
            box_coords (list):
                Bounding box coordinates for each image in the batch.
            device (str):
                Device to run inference on.

        Returns:
            pred_info (list):
                Tuple of masks and scores for each image in the batch.

        """
        model.eval().to(device)

        if isinstance(batch_data, torch.Tensor):
            batch_data = batch_data.cpu().numpy()  

        with torch.inference_mode():
            masks, scores = model(batch_data, point_coords, box_coords)
        return masks, scores

    def _encode_image(self: SAM, image: np.ndarray) -> np.ndarray:
        """Encodes the image for feature extraction."""
        self.predictor.set_image(image)

    def load_state_dict(self: SAM, state_dict: str, **kwargs) -> None:
        """Loads model weights from specified state dictionary."""
        self.model.load_state_dict(state_dict, **kwargs)

    @staticmethod
    def preproc(image: np.ndarray) -> np.ndarray:
        """Pre-processes an image - Converts it into a format accepted by SAM (HWC)."""
        # Move the tensor to the CPU if it's a PyTorch tensor
        if isinstance(image, torch.Tensor):
            return image.permute(1, 2, 0).cpu().numpy()

        return image[..., :3]  # Remove alpha channel if present

    @staticmethod
    def postproc(image: np.ndarray) -> np.ndarray:
        """Post-processes an image."""
        return image
